spring.application.name=device-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/devices
spring.datasource.username=devices
spring.datasource.password=devices

spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.enabled=true
